stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/raw.csv
    params:
      - data
      - preprocessing
    outs:
      - data/processed/processed_data.pkl

  train:
    cmd: python src/training.py
    deps:
      - src/training.py
      - data/processed/processed_data.pkl
    params:
      - data
      - model
    metrics:
      - metrics/training/${model.name}_metrics.json:
          cache: false
    outs:
      - models/${model.name}_model.pkl

  evaluate:
    cmd: python src/evaluation.py
    deps:
      - src/evaluation.py
      - models/${model.name}_model.pkl
    metrics:
      - metrics/evaluation/${model.name}_evaluation.json:
          cache: false
    plots:
      - metrics/plots/${model.name}:
          cache: false

  save_comparison:
    cmd: python src/save_comparison.py
    deps:
      - src/save_comparison.py
      - metrics/evaluation/xgboost_evaluation.json
      - metrics/evaluation/lightgbm_evaluation.json
      - metrics/evaluation/random_forest_evaluation.json
    metrics:
      - metrics/comparison/final_model_comparison.json:
          cache: false
      - metrics/comparison/final_model_comparison.csv:
          cache: false