data:
  raw_path: "data/raw/raw.csv"
  processed_path: "data/processed/raw_processed.csv"
  features:
    - "cpu_request"
    - "mem_request" 
    - "cpu_limit"
    - "mem_limit"
    - "runtime_minutes"
    - "controller_kind"
  target: "cpu_usage"
  
preprocessing:
  test_size: 0.2
  random_state: 42
  categorical_columns: ["controller_kind"]
  
model:
  name: "xgboost"
  
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    
  lightgbm:
    n_estimators: 100
    max_depth: 8
    learning_rate: 0.05
    num_leaves: 31
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42