data:
  features:
  - cpu_request
  - mem_request
  - cpu_limit
  - mem_limit
  - runtime_minutes
  - controller_kind
  processed_path: data/processed/raw_processed.csv
  raw_path: data/raw/raw.csv
  target: cpu_usage
model:
  linear_regression:
    copy_X: true
    fit_intercept: true
    n_jobs: null
    positive: false
  name: linear_regression
  random_forest:
    max_depth: 15
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 100
    random_state: 42
  xgboost:
    colsample_bytree: 0.8
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
    subsample: 0.8
preprocessing:
  categorical_columns:
  - controller_kind
  random_state: 42
  test_size: 0.2
