data:
  features:
  - cpu_request
  - mem_request
  - cpu_limit
  - mem_limit
  - runtime_minutes
  - controller_kind
  processed_path: data/processed/raw_processed.csv
  raw_path: data/raw/raw.csv
  target: cpu_usage
model:
  lightgbm:
    colsample_bytree: 0.8
    learning_rate: 0.05
    max_depth: 8
    n_estimators: 100
    num_leaves: 31
    random_state: 42
    subsample: 0.8
  name: random_forest
  random_forest:
    max_depth: 15
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 100
    random_state: 42
  xgboost:
    colsample_bytree: 0.8
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
    subsample: 0.8
preprocessing:
  categorical_columns:
  - controller_kind
  random_state: 42
  test_size: 0.2
